apiVersion: v1
description: An helm chart for blackfire.io v2
name: blackfire
version: 2.1.0
appVersion: 2
home: https://blackfire.io/
sources:
  - http://blackfire.io
maintainers:
  - name: Paolo Mainardi
    email: paolo.mainardi@sparkfabrik.com
    url: https://github.com/paolomainardi
